GET http://localhost:8282/api/auth/profile
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTU5ODYzNTk2MiwiZXhwIjoxNTk4NzIyMzYyfQ.JdXsnFq_ZJ-qnDZGOHRFYAug_gfMWAnFp4Z8fI58f8QHZMUsbcFh8tCxXtSbSU5rbc41c7br_U6Go7w8uaqYbA

###
POST http://localhost:8282/api/auth/signup
Content-Type: application/json

{
  "username": "aaaa",
  "password": "aaaa",
  "role": ["ROLE_ADMIN"]
}

###
POST http://localhost:8282/api/auth/signin
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}
###
POST http://localhost:8282/api/auth/signin
Content-Type: application/json

{
  "username": "teacher",
  "password": "teacher"
}
###
Authorization: Bearer
