GET http://localhost:8282/api/manage/students
Accept: application/json
###
POST http://localhost:8282/api/manage/students
Content-Type: application/json

{
  "firstName": "xxstName Student",
  "lastName": "testSurname Student",
  "address": "testAddress Student",
  "email": "aaa@aaa",
  "hours": 0,
  "phone": "909090",
  "status": "Active",
  "categoryList": ["A"],
  "user":
  {
    "username": "qq431",
    "password": "wserwe123"
  }
}
###
GET http://localhost:8282/api/manage/students/5
Accept: application/json
###
DELETE http://localhost:8282/api/manage/students/1
Accept: application/json
###




###
PUT http://localhost:8282/api/manage/students/1
Content-Type: application/json

{

  "user":
  {

    "username": "qq431"

  }
}
###
POST http://localhost:8282/api/manage/students
Content-Type: application/json

{
"firstName": "xxatestName Student",
"lastName": "testSurname Student",
"address": "testAddress Student",
  "email": "aaa@aaa",
  "hours": 0,
  "status": "Active",
"categoryList": ["B" ],
  "user":
  {
    "username": "3b21",
    "password": "wserwe123"
  }
}
###
POST http://localhost:8282/api/manage/students
Content-Type: application/json

{
"firstName": "xxatestName Student",
"lastName": "testSurname Student",
"address": "testAddress Student",
  "email": "aaa@aaa",
  "hours": 0,
  "status": "Active",
"categoryList": ["A"],
  "user":
  {
    "username": "340",
    "password": "wserwe123"
  }
}
###
POST http://localhost:8282/api/manage/students
Content-Type: application/json

{
"firstName": "xxatestName Student",
"lastName": "testSurname Student",
"address": "testAddress Student",
  "email": "aaa@aaa",
  "hours": 0,
  "status": "Active",
"categoryList": ["A"],
  "user":
  {
    "username": "3453sb21",
    "password": "wserwe123"
  }
}


